### PR TITLE
build(format): setup prettier

### PR DESCRIPTION
**Pull request by denysdovhan**
## Summary

This PR introduces Prettier to enforce a common code style. Prettier will be run automatically on every commit.

`yarn format` must be run on the repo after merging this PR.

## How did you test this change?

`yarn format`

### CODE REVIEW

**Comment by denysdovhan** [comment]
@tyv @Fer0x anyone? It's open for two weeks already.

**Review by tyv — APPROVED** [review]

**Comment by Fer0x** [comment]
@denysdovhan result  of `yarn format`:
``` 101 files changed, 1912 insertions(+), 1849 deletions(-)```
Should all code be processed with new rules within this PR?

**Comment by denysdovhan** [comment]
@Fer0x I thought it's a better idea to run format in master. This would cause merge conflicts anyway.

**Comment by Fer0x** [comment]
Some controversial rules. I'm ok with first one, but second one looks weird.

image

image

**Comment by denysdovhan** [comment]
@Fer0x this is the way prettier works. We can increase `printWidth` from `80` to, let's say, `100` or `120`. But if the line is longer it will be formatted anyway to fit the line.

**Comment by Fer0x** [comment]
@denysdovhan now I remember why we abandoned prettier in auto-cms ;)

**Pull request merged**
